# Generated by Django 2.2.1 on 2019-05-23 12:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0006_periodictask_priority'),
        ('celerydemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockedSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clocked_time', models.DateTimeField(help_text='Run the task at clocked time', verbose_name='Clock Time')),
                ('enabled', models.BooleanField(default=True, help_text='Set to False to disable the schedule', verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'clocked',
                'verbose_name_plural': 'clocked',
                'ordering': ['clocked_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomPeriodicTask',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.PeriodicTask')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end_time')),
                ('every', models.IntegerField(default=1, verbose_name='every')),
                ('scheduler_type', models.CharField(blank=True, choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=24, null=True, verbose_name='scheduler_type')),
                ('monthly_type', models.CharField(blank=True, choices=[('monthly_day', 'Monthly Day'), ('monthly_last_day', 'Monthly last Day'), ('monthly_first_week', 'Monthly First Week'), ('monthly_second_week', 'Monthly Second Week'), ('monthly_third_week', 'Monthly Third Week'), ('monthly_fourth_week', 'Monthly Fourth Week'), ('monthly_last_week', 'Monthly Last Week')], max_length=24, null=True, verbose_name='monthly_type')),
                ('max_run_count', models.PositiveIntegerField(blank=True, null=True)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('last_executed_days', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('clocked', models.ForeignKey(blank=True, help_text='Clocked Schedule to run the task on.  Set only one schedule type, leave the others null.', null=True, on_delete=django.db.models.deletion.CASCADE, to='celerydemo.ClockedSchedule', verbose_name='Clocked Schedule')),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
    ]
