# Generated by Django 2.2.1 on 2019-05-24 09:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0011_auto_20190508_0153'),
        ('celerydemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPeriodicTask',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.PeriodicTask')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end_time')),
                ('every', models.IntegerField(default=1, verbose_name='every')),
                ('scheduler_type', models.CharField(blank=True, choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=24, null=True, verbose_name='scheduler_type')),
                ('monthly_type', models.CharField(blank=True, choices=[('DAY', 'Day'), ('FIRSTWEEK', 'First Week'), ('SECONDWEEK', 'Second Week'), ('THIRDWEEK', 'Third Week'), ('FOURTHWEEK', 'Fourth Week'), ('LASTWEEK', 'Last Week'), ('LASTDAY', 'Last Day')], max_length=24, null=True, verbose_name='monthly_type')),
                ('max_run_count', models.PositiveIntegerField(blank=True, null=True)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('last_executed_days', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
    ]
