# Generated by Django 2.2.1 on 2019-05-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celerydemo', '0002_clockedschedule_customperiodictask'),
    ]

    operations = [
        migrations.AddField(
            model_name='customperiodictask',
            name='every',
            field=models.IntegerField(default=1, verbose_name='every'),
        ),
        migrations.AddField(
            model_name='customperiodictask',
            name='period',
            field=models.CharField(blank=True, choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=24, null=True, verbose_name='period'),
        ),
        migrations.AlterField(
            model_name='clockedschedule',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Set to False to disable the schedule', verbose_name='Enabled'),
        ),
    ]
