# Generated by Django 2.2.1 on 2019-05-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celerydemo', '0003_auto_20190520_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='customperiodictask',
            name='max_run_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
