# Generated by Django 2.2.1 on 2019-05-22 11:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celerydemo', '0003_customperiodictask_last_executed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customperiodictask',
            name='last_executed_days',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
